#!/bin/bash

echo "########################################################"
echo "Running pre_start"
source "${OPENSHIFT_DATA_DIR}.envvars"
echo "${OPENSHIFT_DATA_DIR}.envvars"
cat ${OPENSHIFT_DATA_DIR}.envvars